### ISSUE TITLE
Screenshot errors

### ISSUE THREAD

**Issue by zannallan** [zannallan/responsive-section#1]
Hi, so I've finished the whole assignment and it looks great on my browser but markbot is saying it doesn't show with the screenshots, saying there is a 94% difference??? I need help please! Thanks
@thomasjbradley

**Comment by thomasjbradley** [comment]
Did you end up figuring this out? My Markbot is showing a complete pass on all the screenshots.

![Screen Shot 2019-11-19 at 10 12 35 PM](https://user-images.githubusercontent.com/105192/69206081-bceda400-0b19-11ea-95ad-798a2243de79.png)

**Comment by zannallan** [comment]
Oh its working now! That was weird. I don't know why it was doing that before. Thanks!
